Cpu topo flag
sjenning/kubernetes pull request #5
Opened 2017-06-30 15:15 UTC by flyingcougar

Added:
- cpu manager flag to kubelet
- cpu topology from cadvisor

Next step:
add selecting cores based on topology

2017-06-30 19:34 UTC, sjenning requested changes
Thanks! Just a few comments.

2017-06-30 19:34 UTC, sjenning commented on pkg/kubelet/cpumanager/cpu_manager.go
> +func NewManager(policyTYpe string, cr internalapi.RuntimeService, kletGetter kletGetter, statusProvider status.PodStatusProvider) (Manager, error) {
s/policyTYpe/policyType

2017-06-30 19:34 UTC, sjenning commented on pkg/kubelet/cpumanager/cpu_manager.go
> +	case "noop":
lets create `type PolicyName string` and create a const in each policy file for these names rather than using raw strings everywhere

2017-06-30 19:34 UTC, sjenning commented on pkg/kubelet/cpumanager/cpu_manager.go
> +	if m.policy.Name() == "noop" {
raw string

2017-06-30 19:34 UTC, sjenning commented on pkg/apis/componentconfig/v1alpha1/defaults.go
> +		obj.CPUManagerPolicy = "noop"
raw string (see below)

2017-06-30 19:34 UTC, sjenning commented on pkg/kubelet/cpumanager/cpu_manager_test.go
> +//import (
Connor removed this file.  If you rebase, all this commenting out will just go away.

2017-06-30 19:34 UTC, sjenning commented on pkg/kubemark/hollow_kubelet.go
> +	c.CPUManagerPolicy = "noop"
raw string

2017-07-03 10:25 UTC, flyingcougar commented on pkg/kubelet/cpumanager/cpu_manager_test.go
> +//import (
hmm... this file is still present on your branch:
https://github.com/sjenning/kubernetes/blob/cpu-manager-poc/pkg/kubelet/cpumanager/cpu_manager_test.go

I have commented it out since `discoverTopology` function no longer uses `proc/cpuinfo`
I need to figure out some other way to test it

2017-07-03 10:27 UTC, flyingcougar commented on pkg/kubelet/cpumanager/cpu_manager.go
> +func NewManager(policyTYpe string, cr internalapi.RuntimeService, kletGetter kletGetter, statusProvider status.PodStatusProvider) (Manager, error) {
ok

2017-07-03 10:33 UTC, flyingcougar commented on pkg/kubelet/cpumanager/cpu_manager.go
> +	case "noop":
agree for internals of cpu manager but do you want to use this type also outside ?
`type KubeletConfiguration struct` has multiple variables that are limited in terms of values (`ContainerRuntime`,`CgroupDriver`) and the types are kept as simple types

2017-07-03 12:40 UTC, flyingcougar commented on pkg/kubelet/cpumanager/cpu_manager_test.go
> +//import (
Connor removed file `manger_test.go` while the test is still present in `cpu_manager_test.go`

2017-07-03 13:51 UTC, flyingcougar commented on pkg/kubelet/cpumanager/cpu_manager.go
> +	if m.policy.Name() == "noop" {
ok

2017-07-03 13:57 UTC, sjenning commented on pkg/kubelet/cpumanager/cpu_manager_test.go
> +//import (
ah ok, didn't notice Connor had done a copy-paste rather than a rename in that first commit.

2017-07-03 13:59 UTC, sjenning commented
Might make the PolicyType -> policyType if we aren't going to use it outside the package but that is a nit.  Merging.  Thanks!

2017-07-03 14:00 UTC, merged

2017-07-05 15:45 UTC, ConnorDoyle commented on pkg/kubelet/cpumanager/state/state_mem.go
> -func (s *stateMemory) Topology() *topo.CPUTopology {
@flyingcougar thanks a lot for cleaning this up